language: java
jdk:
  - oraclejdk8
global:
- secure: N+f3zljiZ6e8MMMcxPr8f8ganXlvDDXSLOQXQYGtnM2Q8K5OvEU626B6hUhgNdKcUf7XLzOxWOzz88Sexsw+8aAQISQ0DkBCA9Dmcx6sMTPxatj9BlzLaTBgcmD0QMF6AkdSfc1Dy3JjPxo+nmeWB+ogXtB2o7dkUIU8nRfr4Hus0akWyE1nW8GBz1QXeviUW55Us3+3cj4aSXLD0dY5R/x2I3ndiFecn0uxCp7JieNjxVnZmtgxqetYQ4uWkheHcjR7k5xGyfs6WiYh+1+i06mnrRBWkLJ3Fql4PZl/KdHQZOii0Cv8Cv+eVyHAGoboKdJ3YCKZ3ijmvlr07giLzblIOeFl1lv3JNTdx6OvS2eYW+Pu3lKrW0kQi7nLZJ9/iMCJza/yv041Q6wESBzFCnNyg1G7tCkr15mjWQSlAlEdpOtc1yO2wDiSp8M1Rxq3N9VkRRVTIYOL7ddsQ/XlkqzeNiWvYpn4MQfOZ7d0Hy75nbs9kKBSqFU4nkqkQaBQivul6BpfXO95C1/yLUKvRneQFAffK/gdgCDY7RZjnRM+G3ZSATPTWxDbFTgrNwK9dQY8hNULt7j5d4cHArfQYl+6X2QMlBbLa2M50SBMR6iGWy/sBBildCMZE6FNx5ARXZ0PVTeoEm1RQzyVKZYIkMuXH/kZ5VxA/8F++p3TBSg=

after_script:
- ./fixup.sh
