language: java
jdk:
  - oraclejdk8
global:
- secure: psrmjPyQRcU/YOTvYYFOMQZMzKDGMRZAEn8kEpUrkMWHrXWXjANnSNXrDt3AMvxcZouQS2lkfL8R9k8wYhC8ohR9BZ9iZAWsajv4fDUZoxjNhQlZIshMtbkOyQL+3RX6L5dkANj8CBibs2Mbr3A7lLkG2hAGjpXlA6qJWNmJ+xZy/qepJ9Dp3GhTjBXIIWoPvjQmRA7i8gRrzff93y/8JYuMr2AGFjlImZAMJeXWHxMjs+h5H+/dYfTn5EGv/IbLKjinhBV1/u9itbXIdLvv+MXg9siE4xd061ek5TOf1avPSop1IHCyNWpuTpyq8TvuHtW5F2OnvgBhfS8H7ix5d+VQlLIsyM5T0WxVMPeg0wvTpGJt12OkRXXV+l2NGBU+53ArX7siDbQph6pGb0REW+CgRZQs7nG/J1FAJvINBb94jjiYvApfmn91rzlw53VCr7iByHK8r5z681uGXJhVUDqn8yte6u+XqCuJnI8QgGbhR4e3Yb+k9lQIwk73Pr5jgENdC/88w1HY/JhWfheNU/H25ttonFYf72z9gkSBrGVzqBnarPz7bdPDxuzMC1rBnnPY2yy/ZZiXkoeT5hybEVBqiFnhmQTtwOC6EqbQX1xMJ5uNibHmaeIGvTa2Tu/cRb6Y36M0mgrkyAT71Crt+Zre1n5i+xe6ydCOyh2x34I=

after_script:
- ./fixup.sh
