import java.io.*;
import java.util.List;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

  private String name;
  private List<String> books;

  public Library(List<String> books) {
    this.books = books;
  }
  
  public boolean someLibraryMethod(boolean arg) {
    return !!arg;
  }

  public boolean isEmpty() {
    for (String book: books) System.out.println(book);

    return books.isEmpty();
  }
}
